name: Build and Deploy site

on:
  push:
    branches:
      - gh-pages

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: install hugo
        run: |
          # current "ubuntu-latest" has 0.92.2, which is way too old
          wget https://github.com/gohugoio/hugo/releases/download/v0.134.2/hugo_extended_0.134.2_linux-amd64.deb
          sudo dpkg -i *.deb
          rm *.deb
      - name: Build
        run: hugo
      - uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy:
    name: publish on github pages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
